
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.market': 'Property Market',
    'nav.mylistings': 'My Listings',
    'nav.partners': 'Partners Network',
    'nav.affiliate': 'Wasat Alliance',
    'nav.developer': 'Developer Hub',
    'nav.broker': 'Broker Center',
    'nav.admin': 'Super Admin',
    'nav.payouts': 'Commissions & Payouts',
    'nav.map': 'Interactive Map',
    'nav.valuation': 'AI Valuation',
    'nav.wallet': 'Smart Wallet',
    'nav.matching': 'AI Matching',
    'nav.settings': 'Settings',
    'nav.platform': 'Platform',
    'nav.marketOpen': 'Riyadh Market Open',
    
    // Common
    'common.sar': 'SAR',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.viewDetails': 'View Full Details',
    'common.save': 'Save Changes',
    'common.saved': 'Saved Successfully',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.active': 'Active',
    'common.pending': 'Pending',
    'common.sold': 'Sold',
    'common.draft': 'Draft',
    'common.return': 'Return',
    'common.download': 'Download PDF',
    'common.last12m': 'Last 12 Months',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'common.ban': 'Ban User',

    // Dashboard
    'dash.title': 'Market Overview',
    'dash.updated': 'Last updated: Just now',
    'dash.avgPrice': 'Avg Price / m² (Riyadh)',
    'dash.vsLastMonth': 'vs last month',
    'dash.volume': 'Market Volume',
    'dash.listings': 'Active Listings',
    'dash.mortgage': 'Mortgage Rate',
    'dash.trends': 'Price Trends (SAR/m²)',
    'dash.hotDistricts': 'Hot Districts',
    'dash.heatmap': 'District Performance Heatmap',
    'dash.highGrowth': 'High Growth',
    'dash.moderate': 'Moderate',
    'dash.decline': 'Decline',

    // Developer Dashboard
    'dev.title': 'Developer Dashboard',
    'dev.subtitle': 'Manage projects, track sales performance, and monitor affiliate broker activity.',
    'dev.stats.revenue': 'Total Sales Revenue',
    'dev.stats.units': 'Units Sold',
    'dev.stats.brokers': 'Active Brokers',
    'dev.stats.leads': 'Pipeline Leads',
    'dev.btn.newProject': 'Add Project',
    'dev.projects.title': 'Active Projects',
    'dev.projects.progress': 'Sales Progress',
    'dev.projects.value': 'Project Value',
    'dev.chart.sales': 'Monthly Sales Performance',
    'dev.table.project': 'Project Name',
    'dev.table.units': 'Total Units',
    'dev.table.sold': 'Sold',
    'dev.table.rev': 'Revenue',
    'dev.table.status': 'Status',
    'dev.activity.title': 'Recent Activity',
    'dev.activity.newLead': 'New lead registered for',
    'dev.activity.sold': 'Unit sold in',
    'dev.activity.contract': 'New broker contract signed',

    // Broker Center
    'broker.title': 'Broker Workspace',
    'broker.subtitle': 'Manage clients, access marketing tools, and track your funnel.',
    'broker.quickActions': 'Quick Actions',
    'broker.register': 'Register New Client',
    'broker.marketing': 'Marketing Kit',
    'broker.funnel': 'My Sales Funnel',
    'broker.leads.active': 'Active Leads',
    'broker.leads.conversion': 'Conversion Rate',
    'broker.leads.commission': 'Est. Commission',
    'broker.marketing.social': 'Social Media Assets',
    'broker.marketing.brochure': 'Project Brochures',
    'broker.marketing.link': 'Personalized Link',
    'broker.marketing.qr': 'QR Generator',
    'broker.tools.ai': 'AI Caption Generator',
    'broker.tools.generate': 'Generate Content',
    'broker.tools.desc': 'Generate professional marketing copy for Instagram/Twitter.',
    'broker.form.clientName': 'Client Name',
    'broker.form.clientPhone': 'Client Phone',
    'broker.form.interest': 'Project Interest',
    'broker.form.notes': 'Notes',
    'broker.form.submit': 'Secure Lead & Generate Contract',
    'broker.recentLeads': 'Recent Registrations',
    'broker.join': 'Join the Elite Broker Network',
    'broker.joinDesc': 'Register your license to unlock Developer Affiliate Contracts, Co-Broking Tools, and Lead Protection.',
    'broker.step1': 'License Info',
    'broker.step2': 'Verification',
    'broker.step3': 'Bank Details',
    'broker.complete': 'Complete Registration',
    'broker.trust': 'Trust Score',
    'broker.ecosystem': 'Broker Ecosystem',
    'broker.affiliate': 'Affiliate Network',
    'broker.cobroking': 'Co-Broking',
    'broker.portfolio': 'My Portfolio',
    'broker.pipeline': 'Active Pipeline',
    'broker.performance': 'Performance',
    'broker.conversion': 'Conversion Rate',
    'broker.commYTD': 'Commission YTD',
    'broker.nextPayout': 'Next Payout',
    'broker.leadGen': 'Lead Gen Forms',
    'broker.leadGenDesc': 'Create embedded forms to capture leads.',
    'broker.buildForm': 'Build Form',
    'broker.campaign': 'Campaign Tools',
    'broker.contracts': 'Active Contracts',
    'broker.archive': 'View Archive',
    'broker.profileDetails': 'Profile Details',
    'broker.changePhoto': 'Change Photo',
    'broker.banking': 'Banking',
    'broker.linkedAccount': 'Linked Account',
    'broker.managePayouts': 'Manage Payouts',

    // Admin Dashboard (Super Admin)
    'admin.title': 'Control Tower',
    'admin.subtitle': 'Super Admin: User Verification, Finance, and Dispute Resolution.',
    'admin.stats.users': 'Total Users',
    'admin.stats.active': 'Active Now',
    'admin.stats.revenue': 'Total Commission',
    'admin.stats.health': 'Contracts Today',
    'admin.tabs.users': 'User Management',
    'admin.tabs.kyc': 'KYC Hub',
    'admin.tabs.finance': 'Treasury',
    'admin.tabs.audit': 'Audit & Disputes',
    'admin.table.user': 'User',
    'admin.table.role': 'Role',
    'admin.table.status': 'Status',
    'admin.table.actions': 'Actions',
    'admin.filter.all': 'All Roles',
    'admin.btn.verify': 'Verify',
    'admin.btn.suspend': 'Suspend',
    'admin.kyc.pending': 'Pending Verification',
    'admin.kyc.doc': 'Document ID',
    'admin.kyc.type': 'License Type',
    'admin.audit.log': 'Action Log',
    'admin.audit.time': 'Timestamp',
    'admin.audit.actor': 'Actor',
    'admin.audit.action': 'Action',
    'admin.audit.details': 'Details',
    'admin.finance.subs': 'Subscriptions',
    'admin.finance.pending': 'Pending Payouts',
    'admin.editUser': 'Edit User',

    // Payouts & Tracking System
    'pay.title': 'Commission & Payout Center',
    'pay.subtitle': 'Track your deals lifecycle, manage earnings, and request payouts.',
    'pay.balance.avail': 'Available for Withdrawal',
    'pay.balance.pending': 'Pending Clearance',
    'pay.balance.total': 'Total Earnings (YTD)',
    'pay.btn.withdraw': 'Withdraw Funds',
    'pay.tracker.title': 'Live Deal Tracker',
    'pay.tracker.stage1': 'Lead Locked',
    'pay.tracker.stage2': 'Contract (SPA)',
    'pay.tracker.stage3': 'Verified',
    'pay.tracker.stage4': 'Released',
    'pay.history.title': 'Transaction History',
    'pay.table.ref': 'Reference',
    'pay.table.type': 'Type',
    'pay.table.amount': 'Amount',
    'pay.table.status': 'Status',
    'pay.table.date': 'Date',
    'pay.status.pending': 'Processing',
    'pay.status.cleared': 'Cleared',
    'pay.status.paid': 'Paid',
    'pay.growth': 'Earnings Growth',
    'pay.estComm': 'Est. Commission',
    'pay.lastUpdate': 'Last Update',
    'pay.next': 'Next',

    // Market
    'market.title': 'Property Stock Market',
    'market.subtitle': 'Live trading platform for real estate assets from top developers, brokers, and owners.',
    'market.tab.all': 'Live Market',
    'market.tab.ipo': 'Project IPOs',
    'market.tab.resale': 'Resale Market',
    'market.tab.watchlist': 'Watchlist',
    'market.watchlist.empty': 'Your watchlist is empty. Star properties to track them here.',
    'market.watchlist.title': 'My Watchlist',
    'market.ticker': 'Ticker',
    'market.price': 'Current Price',
    'market.change': '24h Change',
    'market.volume': 'Vol',
    'market.seller': 'Seller',
    'market.developer': 'Developer',
    'market.broker': 'Broker',
    'market.owner': 'Private Owner',
    'market.buy': 'Buy Now',
    'market.bid': 'Place Bid',
    'market.ask': 'Ask Price',
    'market.high': 'High Demand',
    'market.new': 'New Listing',
    'market.modal.details': 'Property Details',
    'market.modal.completion': 'Completion Date',
    'market.modal.status': 'Listing Status',
    'market.modal.type': 'Property Type',
    'market.ipo': 'IPO',
    'market.search': 'Search ticker, location, seller...',
    'market.notFound': 'No properties found',
    'market.tryAdjust': 'Try adjusting your search terms or filters to find what you\'re looking for.',

    // My Listings
    'listings.title': 'My Properties',
    'listings.subtitle': 'Manage your real estate inventory, track performance, and reach more buyers.',
    'listings.stats.total': 'Total Listings',
    'listings.stats.value': 'Inventory Value',
    'listings.stats.views': 'Total Views',
    'listings.stats.leads': 'Active Leads',
    'listings.btn.add': 'List New Property',
    'listings.search': 'Search inventory...',
    'listings.card.views': 'Views',
    'listings.card.clicks': 'Clicks',
    'listings.card.ctr': 'CTR',
    'listings.action.boost': 'Boost Listing',
    'listings.action.ai': 'AI Insights',
    'listings.status.active': 'Published',
    'listings.status.review': 'In Review',
    'listings.empty': 'No properties listed yet.',
    'listings.boostAlert': 'Boost feature coming soon! This will prioritize your listing in search results.',

    // Partners Network
    'partners.title': 'Partners & Network',
    'partners.subtitle': 'Connect with top-ranked developers and brokers. Automate your cooperation contracts.',
    'partners.tab.developer': 'Developers',
    'partners.tab.broker': 'Brokers',
    'partners.tab.marketer': 'Marketers',
    'partners.score': 'Nawafiz Trust Score',
    'partners.collab': 'Cooperation Rate',
    'partners.deals': 'Deals Closed',
    'partners.inventory': 'Active Inventory',
    'partners.btn.view': 'View Portfolio',
    'partners.btn.collab': 'Collaborate',
    'partners.modal.inventory': 'Partner Inventory',
    'partners.modal.contract': 'E-Contracting',
    'partners.contract.gen': 'Generate Contract',
    'partners.contract.desc': 'This will generate a legally binding brokerage cooperation agreement based on the terms below.',
    'partners.contract.terms': 'Agreed Commission Split',
    'partners.contract.sign': 'Digital Sign & Send',
    'partners.contract.success': 'Contract Signed & Sent!',
    'partners.verified': 'Verified Partner',
    'partners.analytics.totalComm': 'Total Commission Generated',
    'partners.analytics.avgDeal': 'Average Deal Value',
    'partners.analytics.successRate': 'Success Rate by Type',
    'partners.analytics.growth': 'YoY Growth',
    'partners.rank.top': 'Top Rated',
    'partners.about': 'About Partner',
    'partners.performance': 'Deal Performance',
    'partners.rating': 'Client Rating',
    'partners.response': 'Response Rate',
    'partners.contact': 'Contact Information',
    'partners.request': 'Request Collaboration',
    'partners.activeProjects': 'Active Projects',
    'partners.avgPrice': 'Avg Price',
    'partners.commission': 'Commission',
    'partners.terms': 'Collaboration Terms',
    'partners.sai': 'Standard Commission (Sa\'i)',
    'partners.split': 'Your Split Share',
    'partners.duration': 'Contract Duration',
    'partners.agreement': 'Brokerage Agreement',
    'partners.active': 'Agreement Active!',

    // Affiliate Network
    'aff.title': 'Wasat Alliance Network',
    'aff.subtitle': 'The B2B Marketplace connecting Developers with Brokers. Sign contracts instantly and protect your leads.',
    'aff.tab.projects': 'Marketplace',
    'aff.tab.cobroking': 'Co-Broking Board',
    'aff.tab.leads': 'My Lead Vault',
    'aff.tab.wallet': 'Wallet',
    'aff.btn.market': 'Start Marketing',
    'aff.btn.addlead': 'Add Lead',
    'aff.comm': 'Commission',
    'aff.contract.title': 'Contract Agreement',
    'aff.contract.sign': 'I Agree & Sign (OTP)',
    'aff.contract.processing': 'Processing...',
    'aff.lead.name': 'Client Name',
    'aff.lead.phone': 'Client Phone (05...)',
    'aff.lead.submit': 'Secure Lead',
    'aff.lead.success': 'Lead Secured for 60 Days',
    'aff.lead.conflict': 'Client already reserved by another broker',
    'aff.lead.protected': 'Protected until',
    
    // Business Introducer Protocol & Co-Broking
    'aff.contract.type.a': 'Type A: Marketing & Referral Agreement',
    'aff.contract.type.b': 'Type B: Non-Disclosure (NDA) & Commission Split',
    'aff.contract.type.c': 'Type C: Buyer Broker Agreement',
    'aff.contract.signBtn': 'Sign Digitally',
    'aff.contract.terms': 'Terms & Conditions',
    'aff.contract.reveal': 'Sign NDA to Reveal',
    'aff.contract.masked': 'Contact Info Hidden',
    'aff.contract.signed': 'Contract Active',
    'aff.contract.generate': 'Generate Contract',
    'aff.protection.days': 'days left',
    'aff.protection.expired': 'Protection Expired',
    'aff.protection.active': 'Active Protection',
    'aff.cobroking.title': 'Co-Broking Requests',
    'aff.cobroking.haveBuyer': 'Have Buyer',
    'aff.cobroking.haveProperty': 'Have Property',
    'aff.cobroking.split': 'Commission Split',
    'aff.cobroking.urgency': 'Urgency',
    'aff.cobroking.verified': 'Verified Broker',

    // Map
    'map.search.placeholder': 'Ask AI (e.g. "Villas in North Riyadh under 2M")',
    'map.search.btn': 'AI Search',
    'map.filter.all': 'All',
    'map.filter.res': 'Residential',
    'map.filter.com': 'Commercial',
    'map.filter.land': 'Land',
    'map.details.price': 'Price',
    'map.details.roi': 'Exp. ROI',
    'map.details.area': 'Area',
    'map.action.directions': 'Directions',
    'map.action.deal': 'Make a Deal',
    'map.action.share': 'Share Location',
    'map.status.opportunity': 'Hot Opportunity',
    'map.status.new': 'New',
    'map.mode.standard': 'Standard',
    'map.mode.heatmap': 'ROI Heatmap',
    'map.mode.satellite': 'Satellite',
    'map.action.tour': '360° Virtual Tour',
    'map.draw': 'Draw Area',
    'map.hot': 'Hot Deal',
    'map.offer': 'Make an Offer',
    'map.insight': 'AI Insight',
    'map.history': 'Price History (SAR/m²)',
    'map.growth': '1Y Growth',
    'map.yield': 'Rental Yield',
    'map.mortgage': 'Est. Monthly Payment',
    'map.downPayment': 'Down Payment',

    // Valuation
    'val.title': 'AI Valuation Engine',
    'val.subtitle': 'Professional grade appraisal using deep market intelligence and predictive AI.',
    'val.details': 'Property Details',
    'val.city': 'City',
    'val.district': 'District',
    'val.type': 'Type',
    'val.area': 'Area (m²)',
    'val.bedrooms': 'Bedrooms',
    'val.age': 'Age (Years)',
    'val.street': 'Street Width',
    'val.direction': 'Facade Direction',
    'val.finishing': 'Finishing Quality',
    'val.estimateBtn': 'Generate Valuation Report',
    'val.analyzing': 'Analyzing Market Data...',
    'val.estValue': 'Estimated Market Value',
    'val.confidence': 'Confidence',
    'val.marketAnalysis': 'Market Intelligence',
    'val.risk': 'Risk Assessment',
    'val.comparables': 'Recent Comparables',
    'val.noValuation': 'No valuation generated yet',
    'val.prompt': 'Fill in the property details to generate a comprehensive AI report.',
    'val.meterPrice': 'Avg. Meter Price',
    'val.locScore': 'Location Score',
    'val.growth': 'Proj. Growth (1Y)',
    'val.rating': 'Property Rating',
    'val.rating.loc': 'Location',
    'val.rating.serv': 'Services',
    'val.rating.price': 'Price Value',
    'val.rating.fut': 'Potential',
    'val.progress': 'AI Valuation in Progress',
    'val.aiConf': 'AI Confidence',
    'val.invRisk': 'Investment Risk',
    'val.marketVol': 'Market Volume',
    'val.trend': 'District Price Trend (6 Mo)',
    'val.intel': 'AI Market Intelligence',
    'val.comps': 'Comparable Transactions',
    'val.soldRecent': 'Sold within last 3 months',
    'val.hotspots': 'Current Market Hotspots',
    'val.live': 'Live Data',
    'val.advanced': 'Advanced Features',
    
    // Valuation Options
    'val.dir.north': 'North',
    'val.dir.south': 'South',
    'val.dir.east': 'East',
    'val.dir.west': 'West',
    'val.fin.core': 'Core & Shell',
    'val.fin.finished': 'Finished',
    'val.fin.deluxe': 'Deluxe',
    'val.fin.vip': 'VIP/Luxury',

    // Wallet
    'wallet.title': 'Smart Wallet',
    'wallet.export': 'Export Report',
    'wallet.add': 'Add Asset',
    'wallet.totalValue': 'Total Portfolio Value',
    'wallet.invested': 'Total Invested Capital',
    'wallet.gains': 'Unrealized Gains',
    'wallet.allocation': 'Asset Allocation',
    'wallet.performance': 'Performance History',
    'wallet.assets': 'Your Assets',
    'wallet.assetsCount': 'Assets',
    'wallet.total': 'Total',

    // Matching
    'match.title': 'Investment Opportunities',
    'match.subtitle': 'AI-driven deal sourcing based on your financial goals and risk profile.',
    'match.profile': 'Filter Opportunities',
    'match.budget': 'Max Budget',
    'match.goal': 'Strategy',
    'match.cities': 'Target Markets',
    'match.risk': 'Risk Tolerance',
    'match.findBtn': 'Scan Market',
    'match.finding': 'AI Scanning Market...',
    'match.topRecs': 'AI Recommendations',
    'match.matchScore': 'Match Score',
    'match.whyFits': 'AI Insight',
    'match.riskFactors': 'Risk Analysis',
    'match.noMatches': 'No opportunities found matching your strict criteria.',
    'match.roi': 'Proj. Annual ROI',
    'match.netYield': 'Net Yield',
    'match.appreciation': 'Cap. Appreciation',
    'match.feasibility': 'Feasibility Study',
    'match.contact': 'Contact Developer',
    'match.strategy.flip': 'Fix & Flip',
    'match.strategy.rent': 'Rental Income',
    'match.strategy.hold': 'Long-term Hold',
    'match.tags.underMarket': 'Under Market Value',
    'match.tags.highYield': 'High Yield',
    'match.tags.emerging': 'Emerging District',
    'match.modal.financials': 'Financial Analysis',
    'match.modal.cashflow': 'Cash Flow Projection',
    'match.modal.capRate': 'Cap Rate',
    'match.modal.noi': 'Net Operating Income',
    'match.modal.coc': 'Cash on Cash Return',
    'match.modal.occupancy': 'Proj. Occupancy',
    'match.modal.appreciation': 'Est. Appreciation',
    'match.modal.download': 'Download Investment Memo',
    'match.modal.talk': 'Talk to Advisor',
    'match.scanning': 'AI Agent Scanning Market',
    'match.scanningDesc': 'Analyzing over 15,000 active listings against your profile criteria, market trends, and risk factors...',
    'match.define': 'Define Your Investment Strategy',
    'match.defineDesc': 'Set your budget and preferences on the left to let our AI find the highest potential opportunities for you.',
    'match.score': 'AI Match Score',
    'match.projRoi': 'Projected ROI',
    'match.investment': 'Investment',
    'match.request': 'Request Details',

    // Chat
    'chat.advisor': 'Nawafiz AI Advisor',
    'chat.online': 'Online',
    'chat.placeholder': 'Ask about Riyadh market...',
    'chat.welcome': 'Hello! I am Nawafiz AI. Ask me about real estate prices, market trends in Saudi Arabia, or investment advice.',

    // Settings
    'settings.title': 'Settings & Preferences',
    'settings.account': 'Account Settings',
    'settings.general': 'General',
    'settings.users': 'User Management',
    'settings.name': 'Display Name',
    'settings.email': 'Email Address',
    'settings.role': 'Account Role',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.emailNotif': 'Email Updates',
    'settings.pushNotif': 'Push Notifications',
    'settings.newsletter': 'Weekly Newsletter',
    'settings.switchUser': 'Switch User',
    'settings.active': 'Active',
    'settings.switch': 'Switch',
    'settings.addUser': 'Add New User',
    'settings.newUser': 'New User Details',
    'settings.role.investor': 'Investor - Full Access',
    'settings.role.agent': 'Real Estate Broker - Market Tools', // Updated
    'settings.role.admin': 'Admin - Management Only',
    'settings.role.developer': 'Developer - Projects Management',
  },
  ar: {
    // Nav
    'nav.dashboard': 'لوحة البيانات',
    'nav.market': 'السوق العقاري',
    'nav.mylistings': 'عروضي العقارية',
    'nav.partners': 'شبكة الشركاء',
    'nav.affiliate': 'تحالف وسط',
    'nav.developer': 'مركز المطورين',
    'nav.broker': 'مركز الوسيط',
    'nav.admin': 'برج المراقبة',
    'nav.payouts': 'العمولات والمدفوعات',
    'nav.map': 'الخريطة التفاعلية',
    'nav.valuation': 'التقييم الذكي',
    'nav.wallet': 'المحفظة الذكية',
    'nav.matching': 'الفرص الاستثمارية',
    'nav.settings': 'الإعدادات',
    'nav.platform': 'المنصة',
    'nav.marketOpen': 'سوق الرياض مفتوح',

    // Common
    'common.sar': 'ر.س',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.viewDetails': 'عرض التفاصيل الكاملة',
    'common.save': 'حفظ التغييرات',
    'common.saved': 'تم الحفظ بنجاح',
    'common.close': 'إغلاق',
    'common.delete': 'حذف',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.active': 'نشط',
    'common.pending': 'معلق',
    'common.sold': 'مباع',
    'common.draft': 'مسودة',
    'common.return': 'عودة',
    'common.download': 'تحميل PDF',
    'common.last12m': 'آخر 12 شهر',
    'common.approve': 'قبول',
    'common.reject': 'رفض',
    'common.ban': 'حظر المستخدم',

    // Dashboard
    'dash.title': 'نظرة عامة على السوق',
    'dash.updated': 'آخر تحديث: الآن',
    'dash.avgPrice': 'متوسط السعر / م² (الرياض)',
    'dash.vsLastMonth': 'مقارنة بالشهر الماضي',
    'dash.volume': 'حجم التداول',
    'dash.listings': 'العروض النشطة',
    'dash.mortgage': 'نسبة التمويل العقاري',
    'dash.trends': 'اتجاهات الأسعار (ر.س/م²)',
    'dash.hotDistricts': 'الأحياء الأكثر طلباً',
    'dash.heatmap': 'الخريطة الحرارية لأداء الأحياء',
    'dash.highGrowth': 'نمو مرتفع',
    'dash.moderate': 'متوسط',
    'dash.decline': 'انخفاض',
    
    // Developer Dashboard
    'dev.title': 'واجهة المطور العقاري',
    'dev.subtitle': 'إدارة المشاريع، تتبع أداء المبيعات، ومراقبة نشاط الوسطاء.',
    'dev.stats.revenue': 'إجمالي المبيعات',
    'dev.stats.units': 'وحدات مباعة',
    'dev.stats.brokers': 'وسطاء نشطين',
    'dev.stats.leads': 'العملاء المحتملين',
    'dev.btn.newProject': 'إضافة مشروع',
    'dev.projects.title': 'المشاريع النشطة',
    'dev.projects.progress': 'تقدم المبيعات',
    'dev.projects.value': 'قيمة المشروع',
    'dev.chart.sales': 'أداء المبيعات الشهري',
    'dev.table.project': 'اسم المشروع',
    'dev.table.units': 'إجمالي الوحدات',
    'dev.table.sold': 'مباع',
    'dev.table.rev': 'الإيرادات',
    'dev.table.status': 'الحالة',
    'dev.activity.title': 'النشاط الحديث',
    'dev.activity.newLead': 'عميل جديد مهتم بـ',
    'dev.activity.sold': 'تم بيع وحدة في',
    'dev.activity.contract': 'تم توقيع عقد وساطة جديد',

    // Broker Center (New)
    'broker.title': 'مركز الوسيط',
    'broker.subtitle': 'إدارة العملاء، أدوات التسويق، ومتابعة مسار المبيعات.',
    'broker.quickActions': 'إجراءات سريعة',
    'broker.register': 'تسجيل عميل جديد',
    'broker.marketing': 'الحقيبة التسويقية',
    'broker.funnel': 'قمع المبيعات',
    'broker.leads.active': 'العملاء النشطون',
    'broker.leads.conversion': 'معدل التحويل',
    'broker.leads.commission': 'العمولات المتوقعة',
    'broker.marketing.social': 'منشورات التواصل',
    'broker.marketing.brochure': 'بروشورات المشاريع',
    'broker.marketing.link': 'رابط تسويق شخصي',
    'broker.marketing.qr': 'مولد QR Code',
    'broker.tools.ai': 'صانع المحتوى الذكي',
    'broker.tools.generate': 'إنشاء محتوى',
    'broker.tools.desc': 'أنشئ نصوص تسويقية احترافية لمنصات التواصل الاجتماعي.',
    'broker.form.clientName': 'اسم العميل',
    'broker.form.clientPhone': 'رقم الجوال',
    'broker.form.interest': 'المشروع المهتم به',
    'broker.form.notes': 'ملاحظات',
    'broker.form.submit': 'حماية العميل وإنشاء العقد',
    'broker.recentLeads': 'أحدث التسجيلات',
    'broker.join': 'انضم لشبكة وسطاء النخبة',
    'broker.joinDesc': 'سجل رخصتك العقارية لفتح عقود المطورين، أدوات التعاون، ونظام حماية العملاء.',
    'broker.step1': 'بيانات الرخصة',
    'broker.step2': 'التحقق',
    'broker.step3': 'الحساب البنكي',
    'broker.complete': 'إتمام التسجيل',
    'broker.trust': 'نقاط الثقة',
    'broker.ecosystem': 'نظام الوسطاء',
    'broker.affiliate': 'شبكة التحالف',
    'broker.cobroking': 'التعاون المشترك',
    'broker.portfolio': 'محفظتي العقارية',
    'broker.pipeline': 'الصفقات النشطة',
    'broker.performance': 'مؤشرات الأداء',
    'broker.conversion': 'معدل الإغلاق',
    'broker.commYTD': 'عمولات السنة',
    'broker.nextPayout': 'الدفعة القادمة',
    'broker.leadGen': 'نماذج جمع العملاء',
    'broker.leadGenDesc': 'أنشئ نماذج تسجيل مدمجة لجذب المهتمين.',
    'broker.buildForm': 'بناء نموذج',
    'broker.campaign': 'أدوات الحملات',
    'broker.contracts': 'العقود النشطة',
    'broker.archive': 'الأرشيف',
    'broker.profileDetails': 'بيانات الملف',
    'broker.changePhoto': 'تغيير الصورة',
    'broker.banking': 'البيانات المالية',
    'broker.linkedAccount': 'الحساب المرتبط',
    'broker.managePayouts': 'إدارة المدفوعات',

    // Admin Dashboard (Super Admin)
    'admin.title': 'برج المراقبة',
    'admin.subtitle': 'التحكم الشامل: التحقق من الهويات، الخزينة، وفض النزاعات.',
    'admin.stats.users': 'إجمالي المستخدمين',
    'admin.stats.active': 'نشط الآن',
    'admin.stats.revenue': 'إجمالي العمولات',
    'admin.stats.health': 'عقود اليوم',
    'admin.tabs.users': 'إدارة المستخدمين',
    'admin.tabs.kyc': 'مركز التحقق (KYC)',
    'admin.tabs.finance': 'الخزينة',
    'admin.tabs.audit': 'سجل التدقيق وفض النزاعات',
    'admin.table.user': 'المستخدم',
    'admin.table.role': 'الدور',
    'admin.table.status': 'الحالة',
    'admin.table.actions': 'الإجراءات',
    'admin.filter.all': 'جميع الأدوار',
    'admin.btn.verify': 'توثيق',
    'admin.btn.suspend': 'إيقاف',
    'admin.kyc.pending': 'طلبات التحقق المعلقة',
    'admin.kyc.doc': 'رقم الوثيقة',
    'admin.kyc.type': 'نوع الترخيص',
    'admin.audit.log': 'سجل العمليات',
    'admin.audit.time': 'الوقت',
    'admin.audit.actor': 'المنفذ',
    'admin.audit.action': 'الإجراء',
    'admin.audit.details': 'التفاصيل',
    'admin.finance.subs': 'الاشتراكات',
    'admin.finance.pending': 'دفعات معلقة',
    'admin.editUser': 'تعديل المستخدم',

    // Payouts & Tracking System
    'pay.title': 'نظام التتبع والعمولات',
    'pay.subtitle': 'تتبع دورة حياة الصفقات، إدارة الأرباح، وطلب المدفوعات.',
    'pay.balance.avail': 'الرصيد المتاح للسحب',
    'pay.balance.pending': 'عمولات معلقة',
    'pay.balance.total': 'إجمالي الأرباح (السنوي)',
    'pay.btn.withdraw': 'سحب الرصيد',
    'pay.tracker.title': 'تتبع الصفقة المباشر',
    'pay.tracker.stage1': 'حماية العميل',
    'pay.tracker.stage2': 'توقيع العقد',
    'pay.tracker.stage3': 'التوثيق',
    'pay.tracker.stage4': 'إيداع العمولة',
    'pay.history.title': 'سجل العمليات',
    'pay.table.ref': 'المرجع',
    'pay.table.type': 'النوع',
    'pay.table.amount': 'المبلغ',
    'pay.table.status': 'الحالة',
    'pay.table.date': 'التاريخ',
    'pay.status.pending': 'تحت المعالجة',
    'pay.status.cleared': 'مكتمل',
    'pay.status.paid': 'مدفوع',
    'pay.growth': 'نمو الأرباح',
    'pay.estComm': 'العمولة المقدرة',
    'pay.lastUpdate': 'آخر تحديث',
    'pay.next': 'التالي',

    // Market
    'market.title': 'بورصة العقارات',
    'market.subtitle': 'منصة تداول حية للأصول العقارية من كبار المطورين والوسطاء والملاك.',
    'market.tab.all': 'السوق المباشر',
    'market.tab.ipo': 'اكتتابات المشاريع',
    'market.tab.resale': 'سوق إعادة البيع',
    'market.tab.watchlist': 'قائمة المراقبة',
    'market.watchlist.empty': 'قائمة المراقبة فارغة. قم بتمييز العقارات لمتابعتها هنا.',
    'market.watchlist.title': 'قائمتي',
    'market.ticker': 'الرمز',
    'market.price': 'السعر الحالي',
    'market.change': 'تغير 24 ساعة',
    'market.volume': 'حجم التداول',
    'market.seller': 'البائع',
    'market.developer': 'مطور عقاري',
    'market.broker': 'وسيط عقاري',
    'market.owner': 'مالك خاص',
    'market.buy': 'شراء الآن',
    'market.bid': 'قدم عرض',
    'market.ask': 'سعر الطلب',
    'market.high': 'طلب مرتفع',
    'market.new': 'إدراج جديد',
    'market.modal.details': 'تفاصيل العقار',
    'market.modal.completion': 'تاريخ الانتهاء',
    'market.modal.status': 'حالة الإدراج',
    'market.modal.type': 'نوع العقار',
    'market.ipo': 'طرح جديد',
    'market.search': 'بحث بالرمز، الموقع، البائع...',
    'market.notFound': 'لم يتم العثور على عقارات',
    'market.tryAdjust': 'حاول تعديل معايير البحث أو التصنيفات للعثور على ما تبحث عنه.',

    // My Listings
    'listings.title': 'عروضي العقارية',
    'listings.subtitle': 'إدارة المخزون العقاري، تتبع الأداء، والوصول إلى المزيد من المشترين.',
    'listings.stats.total': 'إجمالي العروض',
    'listings.stats.value': 'قيمة المخزون',
    'listings.stats.views': 'إجمالي المشاهدات',
    'listings.stats.leads': 'العملاء المحتملين',
    'listings.btn.add': 'إدراج عقار جديد',
    'listings.search': 'بحث في المخزون...',
    'listings.card.views': 'مشاهدة',
    'listings.card.clicks': 'نقرات',
    'listings.card.ctr': 'معدل النقر',
    'listings.action.boost': 'ترويج الإعلان',
    'listings.action.ai': 'تحليل الذكاء الاصطناعي',
    'listings.status.active': 'منشور',
    'listings.status.review': 'تحت المراجعة',
    'listings.empty': 'لا توجد عقارات مدرجة حتى الآن.',
    'listings.boostAlert': 'ميزة الترويج قادمة قريباً! ستمنح إعلانك أولوية في نتائج البحث.',

    // Partners Network
    'partners.title': 'شركاء النجاح',
    'partners.subtitle': 'تواصل مع نخبة المطورين والوسطاء. أتمتة عقود التعاون والوساطة.',
    'partners.tab.developer': 'المطورين',
    'partners.tab.broker': 'المكاتب العقارية',
    'partners.tab.marketer': 'المسوقين',
    'partners.score': 'نقاط ثقة نوافذ',
    'partners.collab': 'نسبة التعاون (السعي)',
    'partners.deals': 'صفقات ناجحة',
    'partners.inventory': 'المحفظة العقارية',
    'partners.btn.view': 'عرض الملف والمحفظة',
    'partners.btn.collab': 'طلب تعاون',
    'partners.modal.inventory': 'المخزون المتاح',
    'partners.modal.contract': 'التعاقد الإلكتروني',
    'partners.contract.gen': 'إنشاء عقد وساطة',
    'partners.contract.desc': 'سيتم إنشاء عقد وساطة عقارية ملزم قانونياً بناءً على شروط التعاون الموضحة.',
    'partners.contract.terms': 'نسبة اقتسام السعي المتفق عليها',
    'partners.contract.sign': 'توقيع وإرسال رقمي',
    'partners.contract.success': 'تم توقيع العقد وإرساله!',
    'partners.verified': 'شريك موثق',
    'partners.analytics.totalComm': 'إجمالي العمولات المولدة',
    'partners.analytics.avgDeal': 'متوسط قيمة الصفقة',
    'partners.analytics.successRate': 'نسبة الإنجاز حسب النوع',
    'partners.analytics.growth': 'النمو السنوي',
    'partners.rank.top': 'الأعلى تقييماً',
    'partners.about': 'نبذة عن الشريك',
    'partners.performance': 'أداء الصفقات',
    'partners.rating': 'تقييم العملاء',
    'partners.response': 'سرعة الاستجابة',
    'partners.contact': 'بيانات التواصل',
    'partners.request': 'طلب شراكة',
    'partners.activeProjects': 'مشاريع نشطة',
    'partners.avgPrice': 'متوسط السعر',
    'partners.commission': 'نسبة السعي',
    'partners.terms': 'شروط التعاون',
    'partners.sai': 'السعي القياسي (العمولة)',
    'partners.split': 'حصتك من السعي',
    'partners.duration': 'مدة العقد',
    'partners.agreement': 'اتفاقية الوساطة',
    'partners.active': 'الاتفاقية نشطة!',

    // Affiliate Network
    'aff.title': 'شبكة وسط للتحالف العقاري',
    'aff.subtitle': 'المنصة الرقمية للربط بين المطورين (العرض) والوسطاء (الطلب). عقود إلكترونية وحفظ حقوق فوري.',
    'aff.tab.projects': 'سوق المشاريع',
    'aff.tab.cobroking': 'منصة التعاون (Co-Broking)',
    'aff.tab.leads': 'بنك العملاء (خزنة الوسطاء)',
    'aff.tab.wallet': 'محفظة العمولات',
    'aff.btn.market': 'بدء التسويق',
    'aff.btn.addlead': 'إضافة عميل',
    'aff.comm': 'العمولة',
    'aff.contract.title': 'اتفاقية العمل',
    'aff.contract.sign': 'أوافق وأوقّع (رمز التحقق)',
    'aff.contract.processing': 'جاري المعالجة...',
    'aff.lead.name': 'اسم العميل',
    'aff.lead.phone': 'جوال العميل (05...)',
    'aff.lead.submit': 'حجز العميل',
    'aff.lead.success': 'تم تأكيد حماية العميل لمدة 60 يوماً',
    'aff.lead.conflict': 'عذراً، العميل مسجل مسبقاً مع وسيط آخر',
    'aff.lead.protected': 'محمي حتى',
    
    // Business Introducer Protocol & Co-Broking
    'aff.contract.type.a': 'النوع A: عقد تسويق وإحالة',
    'aff.contract.type.b': 'النوع B: اتفاقية عدم إفشاء (NDA) وتقاسم السعي',
    'aff.contract.type.c': 'النوع C: عقد وساطة للمشتري',
    'aff.contract.signBtn': 'توقيع إلكتروني',
    'aff.contract.terms': 'الشروط والأحكام',
    'aff.contract.reveal': 'وقّع NDA لكشف البيانات',
    'aff.contract.masked': 'بيانات الاتصال مخفية',
    'aff.contract.signed': 'عقد نشط',
    'aff.contract.generate': 'إنشاء العقد',
    'aff.protection.days': 'يوم متبقي',
    'aff.protection.expired': 'انتهت الحماية',
    'aff.protection.active': 'حماية نشطة',
    'aff.cobroking.title': 'طلبات التعاون',
    'aff.cobroking.haveBuyer': 'معي مشتري',
    'aff.cobroking.haveProperty': 'معي عقار',
    'aff.cobroking.split': 'تقاسم السعي',
    'aff.cobroking.urgency': 'الأولوية',
    'aff.cobroking.verified': 'وسيط موثق',

    // Map
    'map.search.placeholder': 'اسأل الذكاء الاصطناعي (مثلاً: فلل شمال الرياض بأقل من 2 مليون)',
    'map.search.btn': 'بحث ذكي',
    'map.filter.all': 'الكل',
    'map.filter.res': 'سكني',
    'map.filter.com': 'تجاري',
    'map.filter.land': 'أراضي',
    'map.details.price': 'السعر',
    'map.details.roi': 'العائد المتوقع',
    'map.details.area': 'المساحة',
    'map.action.directions': 'الاتجاهات',
    'map.action.deal': 'إتمام الصفقة',
    'map.action.share': 'مشاركة الموقع',
    'map.status.opportunity': 'فرصة ذهبية',
    'map.status.new': 'جديد',
    'map.mode.standard': 'قياسي',
    'map.mode.heatmap': 'الخريطة الحرارية',
    'map.mode.satellite': 'قمر صناعي',
    'map.action.tour': 'جولة افتراضية 360°',
    'map.draw': 'رسم منطقة',
    'map.hot': 'صفقة ساخنة',
    'map.offer': 'تقديم عرض',
    'map.insight': 'رؤية الذكاء الاصطناعي',
    'map.history': 'تاريخ الأسعار (ر.س/م²)',
    'map.growth': 'نمو سنوي',
    'map.yield': 'عائد تأجيري',
    'map.mortgage': 'القسط الشهري التقديري',
    'map.downPayment': 'الدفعة الأولى',

    // Valuation
    'val.title': 'محرك التقييم الذكي',
    'val.subtitle': 'تقييم احترافي باستخدام ذكاء السوق وتوقعات الذكاء الاصطناعي.',
    'val.details': 'تفاصيل العقار',
    'val.city': 'المدينة',
    'val.district': 'الحي',
    'val.type': 'النوع',
    'val.area': 'المساحة (م²)',
    'val.bedrooms': 'غرف النوم',
    'val.age': 'العمر (سنة)',
    'val.street': 'عرض الشارع',
    'val.direction': 'الواجهة',
    'val.finishing': 'جودة التشطيب',
    'val.estimateBtn': 'إصدار تقرير التقييم',
    'val.analyzing': 'جاري تحليل بيانات السوق...',
    'val.estValue': 'القيمة السوقية التقديرية',
    'val.confidence': 'نسبة الثقة',
    'val.marketAnalysis': 'ذكاء السوق',
    'val.risk': 'تقييم المخاطر',
    'val.comparables': 'عقارات مشابهة حديثة',
    'val.noValuation': 'لم يتم إنشاء تقييم بعد',
    'val.prompt': 'أدخل تفاصيل العقار للحصول على تقرير شامل.',
    'val.meterPrice': 'متوسط سعر المتر',
    'val.locScore': 'درجة الموقع',
    'val.growth': 'النمو المتوقع (سنة)',
    'val.rating': 'تصنيف العقار',
    'val.rating.loc': 'الموقع',
    'val.rating.serv': 'الخدمات',
    'val.rating.price': 'القيمة',
    'val.rating.fut': 'المستقبل',
    'val.progress': 'جاري المعالجة بالذكاء الاصطناعي',
    'val.aiConf': 'ثقة الذكاء الاصطناعي',
    'val.invRisk': 'مخاطر الاستثمار',
    'val.marketVol': 'حجم السوق',
    'val.trend': 'اتجاه أسعار الحي (6 أشهر)',
    'val.intel': 'ذكاء السوق العقاري',
    'val.comps': 'صفقات مماثلة',
    'val.soldRecent': 'تم البيع خلال 3 أشهر',
    'val.hotspots': 'أكثر المناطق نشاطاً',
    'val.live': 'بيانات حية',
    'val.advanced': 'مواصفات متقدمة',

    // Valuation Options
    'val.dir.north': 'شمال',
    'val.dir.south': 'جنوب',
    'val.dir.east': 'شرق',
    'val.dir.west': 'غرب',
    'val.fin.core': 'بناء عظم',
    'val.fin.finished': 'مشطب',
    'val.fin.deluxe': 'ديلوكس',
    'val.fin.vip': 'فاخر / VIP',

    // Wallet
    'wallet.title': 'المحفظة العقارية',
    'wallet.export': 'تصدير تقرير',
    'wallet.add': 'إضافة أصل',
    'wallet.totalValue': 'إجمالي قيمة المحفظة',
    'wallet.invested': 'رأس المال المستثمر',
    'wallet.gains': 'الأرباح غير المحققة',
    'wallet.allocation': 'توزيع الأصول',
    'wallet.performance': 'تاريخ الأداء',
    'wallet.assets': 'أصولك',
    'wallet.assetsCount': 'أصول',
    'wallet.total': 'الإجمالي',

    // Matching
    'match.title': 'الفرص الاستثمارية',
    'match.subtitle': 'محرك ذكي لاكتشاف الصفقات بناءً على أهدافك ومخاطرك.',
    'match.profile': 'تصفية الفرص',
    'match.budget': 'أقصى ميزانية',
    'match.goal': 'الاستراتيجية',
    'match.cities': 'الأسواق المستهدفة',
    'match.risk': 'درجة المخاطرة',
    'match.findBtn': 'مسح السوق',
    'match.finding': 'جاري تحليل السوق...',
    'match.topRecs': 'توصيات الذكاء الاصطناعي',
    'match.matchScore': 'نسبة التطابق',
    'match.whyFits': 'تحليل الذكاء الاصطناعي',
    'match.riskFactors': 'تحليل المخاطر',
    'match.noMatches': 'لم يتم العثور على فرص تطابق معاييرك الدقيقة.',
    'match.roi': 'العائد السنوي المتوقع',
    'match.netYield': 'صافي الدخل',
    'match.appreciation': 'النمو الرأسمالي',
    'match.feasibility': 'دراسة جدوى',
    'match.contact': 'تواصل مع المطور',
    'match.strategy.flip': 'تطوير وبيع (Flip)',
    'match.strategy.rent': 'دخل إيجاري',
    'match.strategy.hold': 'استثمار طويل الأمد',
    'match.tags.underMarket': 'أقل من سعر السوق',
    'match.tags.highYield': 'عائد مرتفع',
    'match.tags.emerging': 'منطقة صاعدة',
    'match.modal.financials': 'التحليل المالي',
    'match.modal.cashflow': 'توقعات التدفق النقدي',
    'match.modal.capRate': 'معدل الرسملة (Cap Rate)',
    'match.modal.noi': 'صافي الدخل التشغيلي',
    'match.modal.coc': 'العائد النقدي على النقد',
    'match.modal.occupancy': 'نسبة الإشغال المتوقعة',
    'match.modal.appreciation': 'الزيادة الرأسمالية',
    'match.modal.download': 'تنزيل مذكرة الاستثمار',
    'match.modal.talk': 'تحدث مع مستشار',
    'match.scanning': 'جاري مسح السوق بالذكاء الاصطناعي',
    'match.scanningDesc': 'جاري تحليل أكثر من 15,000 عرض نشط مقابل معاييرك واتجاهات السوق ومؤشرات المخاطر...',
    'match.define': 'حدد استراتيجيتك الاستثمارية',
    'match.defineDesc': 'حدد ميزانيتك وتفضيلاتك على اليمين للسماح للذكاء الاصطناعي بالعثور على الفرص ذات الإمكانات الأعلى لك.',
    'match.score': 'نسبة المطابقة',
    'match.projRoi': 'العائد المتوقع',
    'match.investment': 'قيمة الاستثمار',
    'match.request': 'طلب التفاصيل',

    // Chat
    'chat.advisor': 'مستشار نوافذ',
    'chat.online': 'متصل',
    'chat.placeholder': 'اسأل عن سوق الرياض...',
    'chat.welcome': 'مرحباً! أنا نوافذ AI. اسألني عن أسعار العقارات، اتجاهات السوق، أو نصائح استثمارية.',

    // Settings
    'settings.title': 'الإعدادات والتفضيلات',
    'settings.account': 'إعدادات الحساب',
    'settings.general': 'عام',
    'settings.users': 'إدارة المستخدمين',
    'settings.name': 'الاسم المعروض',
    'settings.email': 'البريد الإلكتروني',
    'settings.role': 'دور الحساب',
    'settings.language': 'اللغة',
    'settings.notifications': 'الإشعارات',
    'settings.emailNotif': 'تحديثات البريد',
    'settings.pushNotif': 'إشعارات فورية',
    'settings.newsletter': 'النشرة الأسبوعية',
    'settings.switchUser': 'تبديل المستخدم',
    'settings.active': 'نشط',
    'settings.switch': 'تبديل',
    'settings.addUser': 'إضافة مستخدم جديد',
    'settings.newUser': 'تفاصيل المستخدم',
    'settings.role.investor': 'مستثمر - وصول كامل',
    'settings.role.agent': 'وسيط عقاري - أدوات السوق', // Updated
    'settings.role.admin': 'مسؤول - إدارة فقط',
    'settings.role.developer': 'مطور - إدارة المشاريع',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
